export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_CURRENT_USER_DATA = "GET_CURRENT_USER_DATA";
export const LOGOUT_USER = "LOGOUT_USER";
export const UPDATE_USER_NAME = "UPDATE_USER_NAME";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const LOADING_START = "LOADING_START";
export const LOADING_END = "LOADING_END";

export const SET_FRIEND_LIST = "SET_FRIEND_LIST";
export const ADD_FRIEND = "ADD_FRIEND";
export const DELET_FRIEND = "DELETE_FRIEND";
export const LOAD_FRIEND_START = "LOAD_FRIEND_START";
export const LOAD_FRIEND_END = "LOAD_FRIEND_END";
//export const GET_FRIENDS_BYIDS = "GET_FRIENDS_BYIDS";

export const LOAD_EVENT_START = "LOAD_EVENT_START";
export const LOAD_EVENT_END = "LOAD_EVENT_END";
export const ADD_EVENT = "ADD_EVENT";
export const SET_CURRENT_EVENT = "SET_CURRENT_EVENT";
export const SET_EVENT_LIST = "SET_EVENT_LIST";
export const DELETE_EVENT = "DELETE_EVENT";
export const DELETE_BILL = "DELETE_BILL";

export const SET_CURRENT_BILL = "SET_CURRENT_BILL";
export const GET_BILLS_BYEVENT = "GET_BILLS_BYEVENT";
